# Generated by Django 5.1.3 on 2024-11-23 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_targetplan_investment_type_targetplan_lumpsum_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
